version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py

# Agar aap MkDocs use kar rahe hain toh niche wala block use karein:
mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: requirements.txt
